version: '3.4'

services:
  database:
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db:/tmp/data

  financeapi:
    # image: financeapi
    build:
      context: .
      dockerfile: FinanceApi/Dockerfile
    ports:
      - 5000:5000
    environment:
      DB__Host: database
      DB__User: postgres
      DB__Password: ${DB_PASSWORD}
      DB__Database: postgres
      GitHub__ClientId: ${GH_CLIENT_ID}
      GitHub__ClientSecret: ${GH_CLIENT_SECRET}
    depends_on:
      - "database"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw

volumes:
  db:
