global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Text.Json;
global using System.Threading.Tasks;
global using FinanceApi.Exceptions;
global using FinanceApi.Extensions;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging;
global using MediaTypeNames = System.Net.Mime.MediaTypeNames;